package com.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-04-24T14:15:54.946+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://server.com/", name = "IncidentPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IncidentPortType {

    @WebMethod
    @RequestWrapper(localName = "reportIncident", targetNamespace = "http://server.com/", className = "com.server.ReportIncident")
    @ResponseWrapper(localName = "reportIncidentResponse", targetNamespace = "http://server.com/", className = "com.server.ReportIncidentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.server.OutputReportIncident reportIncident(
        @WebParam(name = "input", targetNamespace = "http://server.com/")
        com.server.InputReportIncident input
    );

    @WebMethod
    @RequestWrapper(localName = "statusIncident", targetNamespace = "http://server.com/", className = "com.server.StatusIncident")
    @ResponseWrapper(localName = "statusIncidentResponse", targetNamespace = "http://server.com/", className = "com.server.StatusIncidentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.server.OutputStatusIncident statusIncident(
        @WebParam(name = "input", targetNamespace = "http://server.com/")
        com.server.InputStatusIncident input
    );
}
