package com.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-04-24T14:15:54.956+05:30
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "Incident",
                  wsdlLocation = "http://localhost:8090/camel-soap-cxf-app/webservices/data?wsdl",
                  targetNamespace = "http://server.com/")
public class Incident extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.com/", "Incident");
    public final static QName IncidentPort = new QName("http://server.com/", "IncidentPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/camel-soap-cxf-app/webservices/data?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Incident.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/camel-soap-cxf-app/webservices/data?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Incident(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Incident(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Incident() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Incident(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Incident(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Incident(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IncidentPortType
     */
    @WebEndpoint(name = "IncidentPort")
    public IncidentPortType getIncidentPort() {
        return super.getPort(IncidentPort, IncidentPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IncidentPortType
     */
    @WebEndpoint(name = "IncidentPort")
    public IncidentPortType getIncidentPort(WebServiceFeature... features) {
        return super.getPort(IncidentPort, IncidentPortType.class, features);
    }

}
