
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-04-24T14:15:54.919+05:30
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "Incident",
                      portName = "IncidentPort",
                      targetNamespace = "http://server.com/",
                      wsdlLocation = "http://localhost:8090/camel-soap-cxf-app/webservices/data?wsdl",
                      endpointInterface = "com.server.IncidentPortType")

public class IncidentPortImpl implements IncidentPortType {

    private static final Logger LOG = Logger.getLogger(IncidentPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.server.IncidentPortType#reportIncident(com.server.InputReportIncident input)*
     */
    public com.server.OutputReportIncident reportIncident(com.server.InputReportIncident input) {
        LOG.info("Executing operation reportIncident");
        System.out.println(input);
        try {
            com.server.OutputReportIncident _return = new com.server.OutputReportIncident();
            _return.setCode("Code-243014411");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.server.IncidentPortType#statusIncident(com.server.InputStatusIncident input)*
     */
    public com.server.OutputStatusIncident statusIncident(com.server.InputStatusIncident input) {
        LOG.info("Executing operation statusIncident");
        System.out.println(input);
        try {
             com.server.OutputStatusIncident _return = new com.server.OutputStatusIncident();
            _return.setStatus("Status1482299673");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
