
package com.order.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.3
 * Fri May 06 18:15:56 IST 2016
 * Generated source version: 3.1.3
 */

@XmlRootElement(name = "orderResponse", namespace = "http://order.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderResponse", namespace = "http://order.com/")

public class OrderResponse {

    @XmlElement(name = "return", namespace = "http://order.com/")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

