
package org.app;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.server.Incident;
import com.server.IncidentPortType;
import com.server.InputReportIncident;
import com.server.InputStatusIncident;
import com.server.OutputReportIncident;
import com.server.OutputStatusIncident;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-04-24T14:15:54.706+05:30
 * Generated source version: 3.2.7
 *
 */
public final class CXF_Soap_Service_Incident_Client {

    private static final QName SERVICE_NAME = new QName("http://server.com/", "Incident");

    private CXF_Soap_Service_Incident_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Incident.WSDL_LOCATION;         
      //Here the Incident is service proxy class on client side
        Incident ss = new Incident(wsdlURL, SERVICE_NAME);
        
        //Get the interfcae IncidentPortType implementation proxy on client
        //to connect to the remote service 
        IncidentPortType port = ss.getIncidentPort();
        //org.apache.cxf.jaxws.JaxWsClientProxy@4f3bbf68
        System.out.println("The client port impl is "+port);

        {
        	//Invoke the service opertaions through the port/interfcae from client side
        System.out.println("Invoking reportIncident...");
        //Prepare input data 
        com.server.InputReportIncident input = new com.server.InputReportIncident();
        input.setDetails("Details-519101020");
        input.setEmail("sid@server.net");
        input.setFamilyName("Baba");
        input.setGivenName("Tushar");
        input.setIncidentDate(new Date().toString());
        input.setIncidentId("IncidentId-1349440148");
        input.setPhone("Phone-1326730007");
        input.setSummary("Summary1-Data");
        com.server.OutputReportIncident output = port.reportIncident(input);
        System.out.println("Output reportIncident.result=" + output.getCode());


        }
        {
        System.out.println("Invoking statusIncident...");
        com.server.InputStatusIncident statusInput = new com.server.InputStatusIncident();
        statusInput.setIncidentId("IncidentIdStatus-1621648532");
        com.server.OutputStatusIncident statusOutput = port.statusIncident(statusInput);
        System.out.println("statusIncident.result=" + statusOutput.getStatus());


        }

        System.exit(0);
    }

}
