
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.order;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-05-07T12:56:01.754+05:30
 * Generated source version: 3.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "MyOrderService",
                      portName = "MyOrderPort",
                      targetNamespace = "http://order.com/",
                      wsdlLocation = "http://localhost:8090/CXF-Soap-Orders/services/MyOrderPort?wsdl",
                      endpointInterface = "com.order.OrderEndpoint")
                      
public class MyOrderPortImpl implements OrderEndpoint {

    private static final Logger LOG = Logger.getLogger(MyOrderPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.order.OrderEndpoint#order(java.lang.String  arg0 ,)int  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String order(java.lang.String arg0,int arg1,java.lang.String arg2) { 
        LOG.info("Executing operation order");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return-1099527811";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
