package com.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-05-07T12:56:01.780+05:30
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://order.com/", name = "OrderEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderEndpoint {

    @WebMethod(action = "urn:Order")
    @RequestWrapper(localName = "order", targetNamespace = "http://order.com/", className = "com.order.Order")
    @ResponseWrapper(localName = "orderResponse", targetNamespace = "http://order.com/", className = "com.order.OrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String order(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
